[workspace]
members = [
    "src/nexusblocks_backend/main",
    "src/nexusblocks_backend/platform",
    "src/nexusblocks_backend/platform_manager",
    "src/nexusblocks_backend/user",
    "src/nexusblocks_backend/user_manager",
]
